### ISSUE TITLE
node-sass compatibility

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#12]
This is a meta-issue tracking all the issues necessary for the level of node-sass API compatibility that we want for 1.0.0:

* [x] #7: input options (`file`, `data`, `includePaths`, `indentedSyntax`)
* [x] #8: formatting options (`indentType`, `indentWidth`, `linefeed`, `outputStyle`)
* [x] #9: `importer`
* [ ] #10: `functions`
* [x] #11: `render()` return value
* [x] #109: `render()` error

The following options will not be required for 1.0.0:

* `precision`: Allowing the precision to be customized is challenging in terms of code structure, and may cause some small performance degradation in numerically-intensive tasks due to the lack of constant folding. Since Dart Sass defaults to a much larger precision anyway, we won't support this option for the time being.
* `sourceComments`: Source comments are desirable, but low-priority.
* `omitSourceMapUrl`, `outFile`, `sourceMap`, `sourceMapContents`, `sourceMapEmbed`, `sourceMapRoot`: source map support is not considered blocking for 1.0.0 (see #2).

**Comment by nschonni** [comment]
Not directly related to the API, but the CLI might get re-aligned to the Ruby Sass version https://github.com/sass/node-sass/issues/1719

**Comment by gabrielmaldi** [comment]
Maybe #79 should be added to this list.

**Comment by TheJaredWilcurt** [comment]
What version do you plan to actually support `outputStyle`. Currently it breaks if you pass anything other than `expanded` in.

**Comment by nex3** [comment]
Since alternate output style support is purely cosmetic, it isn't high on the list of priorities right now.

**Comment by jfurrow** [comment]
Thanks @nex3!
