### ISSUE TITLE
Help migrate Node Sass tools to be implementation-agnostic

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#267]
There are a number of Node.js tools out there today that use Node Sass, either directly or as a plugin for a broader build system. In order to make it easier for JS users to use Node Sass, we should help those tools migrate to something that supports Dart Sass as well.

Given a tool that depends on Node Sass and imports it directly, this probably means:
* Removing the Node Sass dependency.
* Changing the API to take the Sass implementation as a parameter. How this work may depend on the specific library involved, but one simple example would be:

  ```js
  var sass = require('gulp-sass')(require('sass'));
  ```
* This will probably be a breaking change to the package, so include a major version bump.

These seem to be the most widely-used integration packages:

* [x] [`sass-loader`](https://www.npmjs.com/package/sass-loader) (for Webpack) — webpack-contrib/sass-loader#435 (pull request: https://github.com/webpack-contrib/sass-loader/pull/573)
* [x] [`react-scripts`](https://www.npmjs.com/package/react-scripts) — https://github.com/facebook/create-react-app/issues/5282
* [x] [`gulp-sass`](https://www.npmjs.com/package/gulp-sass) — dlmanning/gulp-sass#672 (pull request: https://github.com/dlmanning/gulp-sass/pull/694)
* [x] [`broccoli-sass-source-maps`](https://www.npmjs.com/package/broccoli-sass-source-maps) — aexmachina/broccoli-sass-source-maps#26 (pull request: https://github.com/aexmachina/broccoli-sass-source-maps/pull/28)
* [x] [`ember-cli-sass`](https://www.npmjs.com/package/ember-cli-sass) — aexmachina/ember-cli-sass#184 (pull request: https://github.com/aexmachina/ember-cli-sass/pull/186)
* [x] [`grunt-sass`](https://www.npmjs.com/package/grunt-sass) — https://github.com/sindresorhus/grunt-sass/issues/278 (pull request: https://github.com/sindresorhus/grunt-sass/pull/283)
* [ ] [`eyeglass`](https://www.npmjs.com/package/eyeglass) — sass-eyeglass/eyeglass#173

(If anyone has any more packages, let us know!)

**Comment by TheBosZ** [comment]
Rollup has a plugin: https://github.com/differui/rollup-plugin-sass

It supports sending a runtime: https://github.com/differui/rollup-plugin-sass/pull/54

I submitted that PR **specifically** so I could use dart-sass rather than node-sass (node-sass takes about a billion years to compile and isn't any faster on my system).

**Comment by nex3** [comment]
@TheBosZ Thanks for the link! Note though that as long as `rollup-plugin-sass` depends on `node-sass`, you'll still have to deal with the compile times on install.

**Comment by TheBosZ** [comment]
You're welcome!

I know about the dependency problem. I'm going to try to slowly convince people to move over to dart-sass.

I wish there was a way to define a peer dependency with an "OR".

**Comment by xzyfer** [comment]
A note on compiles, you should never have to compile node-sass locally. We literally spend days doing the compilations for every release so you don't have to. Check the release notes for the installed node-sass for the tabled of supported Node versions and operating environments, and update to an appropriate version.

**Comment by TheBosZ** [comment]
@xzyfer It's great that you try to provide multiple versions, but I've often had node-gyp spin up a build step that's annoying.

It also often happens that I'll update node and it'll throw a warning about needing to be recompiled rather than just doing it itself.

Having a "pure javascript" way of doing sass is very desirable from a usability standpoint while node-sass is great for power users.

This also gets around crap like: https://github.com/sass/node-sass/issues/1944

**Comment by robsonsobral** [comment]
@TheBosZ , when that happens, remove the `./node_modules` and the lock files and install again.

**Comment by TheBosZ** [comment]
@robsonsobral That's not an easier than doing the `npm rebuild node-sass --force` dance. Especially when `node_modules` takes around 2 minutes to fully delete on Windows 7.

**Comment by xzyfer** [comment]
No need for the --force flag. Without it the rebuild should take seconds.

**Comment by TheBosZ** [comment]
As an update, rollup-plugin-sass has switched! https://github.com/differui/rollup-plugin-sass/blob/master/CHANGELOG.md

**Comment by nex3** [comment]
Support for Dart Sass has landed in create-react-app: https://github.com/facebook/create-react-app/pull/7496. I'm closing this out, since all the major players now support Dart Sass.
